### PR TITLE
feat(config): Split disabled individual layers from aerial config and bundle them all.

### PR DESCRIPTION
**Pull request by Wentao-Kuang**

### CODE REVIEW

**Comment by Wentao-Kuang** [comment]
Preview link: https://basemaps.linz.govt.nz/?config=s3://linz-basemaps-staging/config/config-CtfUV3mUK8ab14NWyR7finZWG1LX1HPqEsht4LMCCk2F.json.gz#@-41.8899962,174.0492437,z5

**Comment by Wentao-Kuang** [comment]
New preview link: https://basemaps.linz.govt.nz/?config=TmVmbYRQjL9T2JWgyaSie193b4D1qZnBD8hjaSqPFYSsEvEYYhaGYKrcizLPsRbhPyq9t5WDbLiTqnxQb6MKWon79Kaibe2mUoXDYgrFqMUMQdypcYEEgmAQq8ju47K#@-44.1279592,-153.9528242,z3.7298

**Comment by dwsilk** [comment]
The fact that the preview link has New Zealand off to the west isn't something I should be worried about? That's not going to be the default location for our landing page right?

**Comment by Wentao-Kuang** [comment]
> 

That's not the default cause I moved the map and then copy the link. This link will show the default location. https://basemaps.linz.govt.nz/?config=TmVmbYRQjL9T2JWgyaSie193b4D1qZnBD8hjaSqPFYSsEvEYYhaGYKrcizLPsRbhPyq9t5WDbLiTqnxQb6MKWon79Kaibe2mUoXDYgrFqMUMQdypcYEEgmAQq8ju47K

**Review by dwsilk — APPROVED** [review]

**Review by blacha — APPROVED** [review]

**Pull request merged**
